### ISSUE TITLE
CI issues for Pandas

### ISSUE THREAD

**Issue by ggold7046** [pmeier/pmeier#11]
Hi @pmeier,  sorry for opening a new issue as I could not contact you anyway. Could you please look into this ? I tried to contact mroeschke for help,  but he said he doesn't have time.

**Comment by pmeier** [comment]
To be frank: you need to learn some patience. Most people in OSS are volunteers. We have other stuff to do. I saw your pings. I'll respond as soon as I find time.

**Comment by ggold7046** [comment]
The PR is closed, so I commenting in here.

> So if you are stuck on this PR, you can also work on reducing the ignore list.

@pmeier,  I would like to work on the no: 3 part of [this](https://github.com/pandas-dev/pandas/issues/45409#issue-1105272826) from where I started. 

> 3. If errors are found, have the GIthub Action create a new issue (and delete the old one) reporting all the errors and label and Docs and Good First Issue

I would like to work on this one. How to proceed with this ?

**Comment by pmeier** [comment]
Where are you stuck?

**Comment by ggold7046** [comment]
How to do  `GIthub Action create a new issue (and delete the old one) reporting all the errors and label and Docs and Good First Issue` ? Could you give me steps to do it ?

**Comment by pmeier** [comment]
> Could you give me steps to do it ?

Nope. Programming is not about writing code, but rather about solving problems. And this your problem to solve. I'm happy to discuss the details when you have formed a plan and are stuck on the implementation or the like. But you need to do the research on how to tackle the task. I suggest you break it down into smaller chunks, solve them individually, and finally put everything together.

Your PR was not closed because the maintainers don't want to help you. They just don't want to tell you how to solve the problem. Because in that case it would be way faster to just do it themselves. The whole idea of onboarding new contributors is that they afterwards can solve issues by themselves without a large amount of guidance. But if you show no sign of an idea how to solve the issue and already tag people to help you, I would close the PR as well.

**Comment by ggold7046** [comment]
> (and delete the old one)

I don't understand this. Delete which old issue? The links are already all new. And there will be a single PR/broken link, isn't it ?
> reporting all the errors

Report to whom, where ? Any files ?

I found this `softprops/action-gh-release@v1` for creating a  github issue. Is this the one to use ? But this thing is asking for `secrets.GITHUB_TOKEN`, do I need it ?

**Comment by pmeier** [comment]
> > (and delete the old one)
> 
> I don't understand this. Delete which old issue? The links are already all new. And there will be a single PR/broken link, isn't it ?

When the workflow runs and finds broken links it should create an issue like "Here are all the broken links I found. Please fix them". When it runs the second time there is potentially already an issue. So instead of just creating a new one and now having two issues that largely have the same information, the second run should close the first issue if it is still open.

> I found this `softprops/action-gh-release@v1` for creating a github issue. Is this the one to use ?

This action is about creating releases (think tagged versions). You are looking for one that creates issues.

> But this thing is asking for `secrets.GITHUB_TOKEN`, do I need it ?

This is not a problem and expected. If you ask a bot or a workflow to create an issue on a repository, it needs to have permissions to do that. And for bots / workflows, these permissions are communicated through a token. When running in GHA, you have access to `${{ secrets.GITHUB_TOKEN }}` for the repository for exactly this purpose. Nothing to worry about.

**Comment by ggold7046** [comment]
<Details>

```
name: Sphinx Linkcheck and Issue Creation & Delete old issue

on:
  schedule:
    - cron: '0 0 1 * *' # Run monthly on the 1st day of the month

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda
        uses: ./.github/actions/setup-conda 

      - name: Build Pandas
        uses: ./.github/actions/build_pandas 

      - name: Run linkcheck script
        working-directory: ./doc
        run: |
          set -o pipefail
          python make.py linkcheck | tee linkcheck.txt

      - name: Create/Update Linkcheck Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # Get the previous linkcheck issue number if it exists
            previous_issue_number=$(gh issue list --labels "Docs,Good First Issue" --json number --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue delete "$previous_issue_number"
            fi

            # Create a new linkcheck issue
            new_issue_url=$(gh issue create \
              --title "Linkcheck Report - $(date +"%Y-%m-%d")" \
              --labels "Docs,Good First Issue" \
              --body "$(cat linkcheck.txt)")
```
</Details>

Is it right ?

**Comment by pmeier** [comment]
> Is it right ?

Nope, but it is going in the right direction. Some pointers:

1. Instead of having a separate workflow for schedule workflow, we can amend the workflow you implemented previously. Make sure that the issue creation / update only happens when running on a schedule. Since we have PR triggers, we don't want to rapidly close and create new issues whenever we push a commit there.
2. You are currently looking for the old issue by the "Docs" and "Good First Issue" labels. There are likely plenty of them. How are making sure not to close an unrelated one?
3. While good enough for a first draft, the issue should have a better body. It should include some text on what these links mean and how to fix them.

For 2. / 3. I suggest you use a specialized action rather than trying to script one yourself. For example 

- https://github.com/marketplace/actions/create-github-issue
- https://github.com/marketplace/actions/create-an-issue
- https://github.com/marketplace/actions/create-issue-from-file

Compare these (or possible others) and see if one is able to handle all things that we want from it.

**Comment by ggold7046** [comment]
This is the combined workflow file.

<Details>

```
name: Linkcheck
on:
  schedule:
    # Run monthly on the 1st day of the month
    - cron: '0 0 1 * *'
  pull_request:
    paths:
      - ".github/workflows/broken-linkcheck.yml"
      - "doc/make.py"
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda
        uses: ./.github/actions/setup-conda

      - name: Build Pandas
        uses: ./.github/actions/build_pandas

      - name: Run linkcheck script
        working-directory: ./doc
        run: |
          set -o pipefail
          python make.py linkcheck | tee linkcheck.txt

      - name: Create or Update Linkcheck Issue
        if: github.event_name == 'schedule'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Linkcheck Report - $(date +'%Y-%m-%d')"
          labels: "Docs,Good First Issue,Linkcheck-Report"
          body: |
            ### Linkcheck Report

            This issue is automatically created or updated to report broken links found during the linkcheck process.

            #### Summary:

            - Number of Broken Links: X
            - Date: $(date +"%Y-%m-%d")

            #### Broken Links:

            ```
            $(cat linkcheck.txt)
           ```

      - name: Display broken links
        if: failure() && github.event_name == 'schedule'
        working-directory: ./doc
        run: grep broken linkcheck.txt

```
</Details>

**Comment by ggold7046** [comment]
@pmeier

**Comment by pmeier** [comment]
Look like a good start. With CI usually something comes up when you actually try it. But i think you are in a state now to try. Some comments:

- `title: "Linkcheck Report - $(date +'%Y-%m-%d')"`
  I don't think you can use bash commands there. Same for the `body` of the action. You need to come up with a scheme to set these variables before and only use them here.

I think the best way for you to test this is to create your own repository as CI playground. In there create an action that writes a dummy file `linkcheck.txt` that resembles the original one. And with that you play with all the settings until it does what you want it to do. Of course I wouldn't put that on the schedule trigger. That is something that you can add later on only for pandas.

**Comment by ggold7046** [comment]
@pmeier, How would I know if a new issue has been created or not in my forked repo ? There is no issue tab in my repo.

**Comment by pmeier** [comment]
I don't know how your fork is set up. To enable issues, you should click on the Settings icon in the top bar of the repository

![image](https://github.com/pmeier/pmeier/assets/6849766/7d5aca36-7b1f-497a-b605-108b4cf3d30e)

I can't see that, because I don't have permissions, but you should. And in there you scroll down and check the box:

![image](https://github.com/pmeier/pmeier/assets/6849766/e68017d4-e523-42b3-a6de-5ad093f936a2)

**Comment by ggold7046** [comment]
Got the issue tab in my repo.

<Details>

```
name: Linkcheck
on:
  #schedule:
  # Run monthly on the 1st day of the month
  #  - cron: '0 0 1 * *'
  pull_request:
    paths:
      - ".github/workflows/broken-linkcheck.yml"
      - "doc/make.py"
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda
        uses: ./.github/actions/setup-conda

      - name: Build Pandas
        uses: ./.github/actions/build_pandas

      - name: Run linkcheck script
        working-directory: ./doc
        run: |
          set -o pipefail
          python make.py linkcheck | tee linkcheck.txt

      - name: Create or Update Linkcheck Issue
        if: github.event_name == 'schedule'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          current_date: $(date +"%Y-%m-%d")
          title: "Linkcheck Report - ${{ env.current_date }}"
          labels: "Docs,Good First Issue,Linkcheck-Report"
          body: |
            ### Linkcheck Report

            This issue is automatically created or updated to report broken links found during the linkcheck process.

            #### Summary:

            - Number of Broken Links: X
            - Date: ${{ env.current_date }}

            #### Broken Links:

            ```
            $(cat linkcheck.txt)
            ```

      - name: Display broken links
        if: failure() && github.event_name == 'schedule'
        working-directory: ./doc
        run: grep broken linkcheck.txt
```
</Details>

This is the changed workflow. I kept everything same and commented out the schedule one. My all test failed  in my own repo CI run (https://github.com/ggold7046/pandas/pull/2) . But all the test are passed in the pandas PR.
